### ISSUE TITLE
Failed to import on Mac

### ISSUE THREAD

**Issue by qyx268** [1313e/PRISM#15]
**Describe the bug**

importing prism failed and caused IPython (and python) to crash on Mac OS Yosemite

**Minimal example to reproduce**

`$ ipython`
`>> import prism`

![image](https://user-images.githubusercontent.com/15994713/54120376-d3265a80-43f7-11e9-9630-7ff14e095807.png)

**Expected behavior**

**Screenshots**

**Tracebacks**

**System information**

![image](https://user-images.githubusercontent.com/15994713/54120933-64e29780-43f9-11e9-9efc-9dfe8cbf10ee.png)

**Additional context**

**Comment by 1313e** [comment]
Hi @qyx268, it seems that there is something more going on, as the second error message after attempting to import PRISM looks a bit weird to me.
Can you check for me whether or not it is possible to simply execute `import matplotlib.pyplot as plt`?

Also, to make sure these errors are not caused by any bugs I have already fixed, could you make sure you use the latest version of PRISM (v1.1.1)?

**Comment by qyx268** [comment]
I now believe this is related to plotting over ssh rather a bug in PRISM. One needs to specify backend for matplotlib (also on a linux server). It's probably good if PRISM supports this although users can specify backend by themselves.
![image](https://user-images.githubusercontent.com/15994713/54136189-9a987800-441b-11e9-85bc-81cbcc803bb8.png)

Also, the invalid  connection ID issue originally posted can solved by this answer (https://stackoverflow.com/a/35614082). It seems that users have to login to Mac desktop version to have valid connection ID.

**Comment by 1313e** [comment]
Alright, glad that problem is solved.
Sadly, it is not possible for PRISM to allow the backend to be specified, it must be done through matplotlib. If I ever find a good way to do this, I will definitely implement it.
